ALTER TABLE "Sale" ADD COLUMN "lastEditedById" TEXT;
ALTER TABLE "Sale" ADD COLUMN "lastEditedAt" TIMESTAMP(3);

ALTER TABLE "Sale" ADD CONSTRAINT "Sale_lastEditedById_fkey" FOREIGN KEY ("lastEditedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
